import ImageL from "../assets/featured Pages/vu-anh-TiVPTYCG_3E-unsplash.jpg"
import profile1 from "../assets/featured Pages/alexander-hipp-iEEBWgY_6lA-unsplash.jpg"
import Image2 from "../assets/featured Pages/todd-kent-178j8tJrNlc-unsplash.jpg"
import profile2 from "../assets/featured Pages/ryan-hoffman-Ft4p5E9HjTQ-unsplash.jpg"
import Image3 from "../assets/featured Pages/spacejoy-XpbtQfr9Skg-unsplash.jpg"
import profile3 from "../assets/featured Pages/jason-moyer-A73ah5JKtVA-unsplash.jpg"
import Image4 from "../assets/featured Pages/spacejoy-uGWNcejbf2E-unsplash.jpg"
import Image5 from "../assets/featured Pages/sieuwert-otterloo-aren8nutd1Q-unsplash.jpg"
import Image6 from "../assets/featured Pages/sidekix-media-wRzBarqn3hs-unsplash.jpg";
import Image7 from "../assets/featured Pages/ralph-ravi-kayden-mR1CIDduGLc-unsplash.jpg";
import Image8 from "../assets/featured Pages/r-architecture-2gDwlIim3Uw-unsplash.jpg";
import Image9 from "../assets/featured Pages/kara-eads-L7EwHkq1B2s-unsplash.jpg";
import Image10 from "../assets/featured Pages/greg-rivers-rChFUMwAe7E-unsplash.jpg";
import Image11 from "../assets/featured Pages/fomstock-4ojhpgKpS68-unsplash.jpg";
import Image12 from "../assets/featured Pages/digital-marketing-agency-ntwrk-g39p1kDjvSY-unsplash.jpg";

const cardGroup = [
    {
        type: "Apartment",
        price: "$13000",
        img: ImageL,
        name: "Luxury Family Home",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "1",
        bath: "1",
        sqft: "8280",
        profileImg: profile1,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "sale",
    },
    {
        type: "Bungalow",
        price: "$14000",
        img: Image2,
        name: "Renovated Apartment",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "2",
        bath: "2",
        sqft: "5280",
        profileImg: profile2,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
    {
        type: "Bungalow",
        price: "$13000",
        img: Image3,
        name: "Single Family Home",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "3",
        bath: "2",
        sqft: "3280",
        profileImg: profile3,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
    {
        type: "House",
        price: "$11000",
        img: Image4,
        name: "Gorgeous Villa Bay View",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "5",
        bath: "5",
        sqft: "5280",
        profileImg: profile3,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
    {
        type: "Land",
        price: "$17000",
        img: Image5,
        name: "Renovated Apartment",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "4",
        bath: "4",
        sqft: "6280",
        profileImg: profile1,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
    {
        type: "Single Family Home",
        price: "$16000",
        img: Image6,
        name: "Gorgeous Villa Bay View",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "4",
        bath: "2",
        sqft: "9500",
        profileImg: Image9,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
    {
        type: "Apartment",
        price: "$15000",
        img: Image7,
        name: "Renovated Apartment",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "4",
        bath: "3",
        sqft: "10280",
        profileImg: profile2,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
    {
        type: "Condo",
        price: "$12000",
        img: Image8,
        name: "Gorgeous Villa Bay View",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "4",
        bath: "2",
        sqft: "6880",
        profileImg: profile3,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
    {
        type: "Single Family Home",
        price: "$14000",
        img: Image9,
        name: "Renovated Apartment",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "4",
        bath: "6",
        sqft: "12000",
        profileImg: profile1,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
    {
        type: "Apartment",
        price: "$15000",
        img: Image10,
        name: "Luxury Family Home",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "4",
        bath: "6",
        sqft: "5280",
        profileImg: profile1,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
    {
        type: "Villa",
        price: "$19000",
        img: Image11,
        name: "Renovated Apartment",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "4",
        bath: "1",
        sqft: "5280",
        profileImg: profile2,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
    {
        type: "Bungalow",
        price: "$13000",
        img: Image12,
        name: "Luxury Family Home",
        location: "1421 San Pedro St, Los Angeles CA 900015",
        beds: "4",
        bath: "2",
        sqft: "5280",
        profileImg: profile3,
        profileName: "Ali Tufan",
        date: "1 year ago",
        mode: "rent",
    },
];

export default cardGroup